### PR TITLE
fix: support children of quote blocks

### LINKED ISSUE #29: number/bullet list  within blockquote will be ignored
<sub>[Discuss in #**public-issue-29--numberbullet-list-within-blockquote-will-be-ignored**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C03EJ9VLBQD)</sub>

The markdown string blow will produce a empty `Blockquote` notion block using `markdownToBlocks`.

```markdown

> - list item 1
> - list item 2

```

```json
[
  {
    "object": "block",
    "type": "quote",
    "quote": {
      "text": []
    }
  }
]
```

I think it should be keep as rich text just as other block

https://github.com/instantish/martian/blob/master/src/parser/internal.ts#L147-L159

### PR DESCRIPTION
**Pull request by EndBug**
This PR closes #29 
We were previously converting a selection of blocks to rich text, to put inside the quote block.
I first tried to expand the list of supported blocks to almost everyone but the result was not ideal. While testing I ended up finding that if we set a rich text block with empty content, Notion won't display the "Empty quote" box before the children.
I think this is the optimal way to handle quote blocks since we're setting the children without compromising on formatting.

Quote block without any rich text element:
image

Quote block with the empty rich text element:
image

### CODE REVIEW

**Review by marissamarym — APPROVED** [review]

**Comment by zanemcca** [comment]
@marissamarym do you know when this will be released?

**Comment by marissamarym** [comment]
> @marissamarym do you know when this will be released?

just released 👍

**Comment by notzheng** [comment]
> > @marissamarym do you know when this will be released?
> 
> just released 👍

Hi, could you publish it to npm? 

I just found that I had no permission to install from [github packages](https://github.com/instantish/martian/packages/1353091) .

**Comment by zanemcca** [comment]
I would also love to see npm published if you would be so kind @marissamarym? Thanks in advance!

**Comment by EndBug** [comment]
@notzheng @zanemcca The changes are now published at [`@tryfabric/martian@1.2.4`](https://www.npmjs.com/package/@tryfabric/martian/v/1.2.4), sorry for the wait 🙏🏻

**Pull request merged**
